namespace PoolHub.Core.Entities;

public abstract class BaseEntity
{
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAtUtc { get; set; }
}

public class Role : BaseEntity { public int RoleId { get; set; } public string Name { get; set; } = string.Empty; public string? Description { get; set; } public bool IsSystem { get; set; } = true; }
public class User : BaseEntity { public int UserId { get; set; } public Guid PublicId { get; set; } = Guid.NewGuid(); public string FullName { get; set; } = string.Empty; public string Email { get; set; } = string.Empty; public string PasswordHash { get; set; } = string.Empty; public string? PhoneNumber { get; set; } public string? AvatarUrl { get; set; } public bool EmailConfirmed { get; set; } public bool Status { get; set; } = true; public DateTime? LastLoginAtUtc { get; set; } public byte[] RowVersion { get; set; } = []; }
public class UserRole { public int UserId { get; set; } public int RoleId { get; set; } public DateTime AssignedAtUtc { get; set; } = DateTime.UtcNow; public int? AssignedByUserId { get; set; } }
public class RefreshToken : BaseEntity { public int RefreshTokenId { get; set; } public int UserId { get; set; } public string TokenHash { get; set; } = string.Empty; public DateTime ExpiresAtUtc { get; set; } public DateTime? RevokedAtUtc { get; set; } public string? CreatedByIp { get; set; } public string? RevokedByIp { get; set; } public bool IsRevoked { get; set; } }
public class Customer : BaseEntity { public int CustomerId { get; set; } public Guid PublicId { get; set; } = Guid.NewGuid(); public string FullName { get; set; } = string.Empty; public string PhoneNumber { get; set; } = string.Empty; public string? Email { get; set; } public string? Note { get; set; } public bool Status { get; set; } = true; }
public class Floor : BaseEntity { public int FloorId { get; set; } public string Name { get; set; } = string.Empty; public string? Description { get; set; } public int DisplayOrder { get; set; } public bool IsActive { get; set; } = true; }
public class Zone : BaseEntity { public int ZoneId { get; set; } public int FloorId { get; set; } public string Name { get; set; } = string.Empty; public string? Description { get; set; } public int DisplayOrder { get; set; } public bool IsActive { get; set; } = true; }
public class TableType : BaseEntity { public int TableTypeId { get; set; } public string Name { get; set; } = string.Empty; public string Code { get; set; } = string.Empty; public string? Description { get; set; } public int DefaultCapacity { get; set; } public bool IsActive { get; set; } = true; }
public class VenueTable : BaseEntity { public int TableId { get; set; } public Guid PublicId { get; set; } = Guid.NewGuid(); public int ZoneId { get; set; } public int TableTypeId { get; set; } public string TableCode { get; set; } = string.Empty; public string TableName { get; set; } = string.Empty; public int Capacity { get; set; } public decimal PositionX { get; set; } public decimal PositionY { get; set; } public int OperationalStatus { get; set; } = 1; }
public class PricingPlan : BaseEntity { public int PricingPlanId { get; set; } public string Name { get; set; } = string.Empty; public string? Description { get; set; } public bool IsDefault { get; set; } public bool IsActive { get; set; } = true; public DateTime StartsAtUtc { get; set; } = DateTime.UtcNow; public DateTime? EndsAtUtc { get; set; } }
public class PricingPlanRule : BaseEntity { public int PricingPlanRuleId { get; set; } public int PricingPlanId { get; set; } public int TableTypeId { get; set; } public int DayOfWeek { get; set; } public TimeSpan StartTime { get; set; } public TimeSpan EndTime { get; set; } public decimal HourlyRate { get; set; } public int MinimumMinutes { get; set; } public int BillingBlockMinutes { get; set; } public bool IsActive { get; set; } = true; }
public class Booking : BaseEntity { public int BookingId { get; set; } public Guid PublicId { get; set; } = Guid.NewGuid(); public int CustomerId { get; set; } public int TableId { get; set; } public int TableTypeId { get; set; } public string BookingCode { get; set; } = string.Empty; public DateTime StartTimeUtc { get; set; } public DateTime EndTimeUtc { get; set; } public int NumberOfGuests { get; set; } public int Status { get; set; } public string? Note { get; set; } public int? ConfirmedByUserId { get; set; } public DateTime? ConfirmedAtUtc { get; set; } public DateTime? CancelledAtUtc { get; set; } }
public class Session : BaseEntity { public int SessionId { get; set; } public Guid PublicId { get; set; } = Guid.NewGuid(); public string SessionCode { get; set; } = string.Empty; public int? BookingId { get; set; } public int StartedByUserId { get; set; } public DateTime StartTimeUtc { get; set; } public DateTime? EndTimeUtc { get; set; } public int Status { get; set; } = 1; }
public class SessionTableAssignment : BaseEntity { public int AssignmentId { get; set; } public int SessionId { get; set; } public int TableId { get; set; } public DateTime AssignedAtUtc { get; set; } public DateTime? ReleasedAtUtc { get; set; } public bool IsPrimary { get; set; } }
public class ProductCategory : BaseEntity { public int CategoryId { get; set; } public string Name { get; set; } = string.Empty; public string Code { get; set; } = string.Empty; public string? Description { get; set; } public bool IsActive { get; set; } = true; }
public class Product : BaseEntity { public int ProductId { get; set; } public int CategoryId { get; set; } public string Name { get; set; } = string.Empty; public string Code { get; set; } = string.Empty; public decimal UnitPrice { get; set; } public int StockQuantity { get; set; } public bool IsActive { get; set; } = true; public byte[] RowVersion { get; set; } = []; }
public class InventoryTransaction : BaseEntity { public int InventoryTransactionId { get; set; } public int ProductId { get; set; } public int QuantityChange { get; set; } public int StockAfter { get; set; } public string Reason { get; set; } = string.Empty; public int? CreatedByUserId { get; set; } }
public class Order : BaseEntity { public int OrderId { get; set; } public Guid PublicId { get; set; } = Guid.NewGuid(); public int SessionId { get; set; } public int CreatedByUserId { get; set; } public int Status { get; set; } = 1; }
public class OrderItem : BaseEntity { public int OrderItemId { get; set; } public int OrderId { get; set; } public int ProductId { get; set; } public int Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal LineTotal { get; set; } }
public class Discount : BaseEntity { public int DiscountId { get; set; } public string Name { get; set; } = string.Empty; public decimal Value { get; set; } public int Type { get; set; } public bool IsActive { get; set; } = true; }
public class Invoice : BaseEntity { public int InvoiceId { get; set; } public Guid PublicId { get; set; } = Guid.NewGuid(); public int SessionId { get; set; } public string InvoiceCode { get; set; } = string.Empty; public decimal SubtotalAmount { get; set; } public decimal DiscountAmount { get; set; } public decimal FinalAmount { get; set; } public int Status { get; set; } = 1; }
public class InvoiceLine : BaseEntity { public int InvoiceLineId { get; set; } public int InvoiceId { get; set; } public string LineType { get; set; } = string.Empty; public string Description { get; set; } = string.Empty; public int Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal LineTotal { get; set; } }
public class InvoiceDiscount : BaseEntity { public int InvoiceDiscountId { get; set; } public int InvoiceId { get; set; } public int DiscountId { get; set; } public decimal DiscountAmount { get; set; } }
public class PaymentMethod : BaseEntity { public int PaymentMethodId { get; set; } public string Name { get; set; } = string.Empty; public string Code { get; set; } = string.Empty; public bool IsActive { get; set; } = true; }
public class Payment : BaseEntity { public int PaymentId { get; set; } public int InvoiceId { get; set; } public int PaymentMethodId { get; set; } public decimal Amount { get; set; } public DateTime PaidAtUtc { get; set; } = DateTime.UtcNow; public int Status { get; set; } = 1; }
public class Notification : BaseEntity { public int NotificationId { get; set; } public int? UserId { get; set; } public string Title { get; set; } = string.Empty; public string Content { get; set; } = string.Empty; public bool IsRead { get; set; } }
public class AuditLog : BaseEntity { public int AuditLogId { get; set; } public int? UserId { get; set; } public string Action { get; set; } = string.Empty; public string EntityName { get; set; } = string.Empty; public string EntityId { get; set; } = string.Empty; public string? Metadata { get; set; } }
