// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoolHub.Infrastructure.Data;

#nullable disable

namespace PoolHub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PoolHubDbContext))]
    [Migration("20260618022314_AddAuthUserRoleRefreshTokenAuditEnhancements")]
    partial class AddAuthUserRoleRefreshTokenAuditEnhancements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PoolHub.Core.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity_name");

                    b.Property<Guid?>("EntityPublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_public_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_values");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("user_agent");

                    b.HasKey("AuditLogId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ActorUserId", "CreatedAtUtc");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Booking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookingId"));

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("booking_code");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<long?>("ConfirmedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_time_utc");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int")
                        .HasColumnName("number_of_guests");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_time_utc");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<long?>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    b.Property<long?>("TableTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_type_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("TableId");

                    b.HasIndex("TableTypeId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Discount", b =>
                {
                    b.Property<long>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("discount_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DiscountId"));

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("applies_to");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DiscountCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("discount_code");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discount_type");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ends_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("max_amount");

                    b.Property<decimal?>("MinTimeSubtotal")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("min_time_subtotal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("starts_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("value");

                    b.HasKey("DiscountId");

                    b.HasIndex("DiscountCode")
                        .IsUnique();

                    b.ToTable("discounts", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Floor", b =>
                {
                    b.Property<long>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("floor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FloorId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("FloorId");

                    b.ToTable("floors", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.InventoryTransaction", b =>
                {
                    b.Property<long>("InventoryTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InventoryTransactionId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reference_type");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int")
                        .HasColumnName("transaction_type");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("unit_cost");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("InventoryTransactionId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Invoice", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("GrandTotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("grand_total_amount");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("invoice_code");

                    b.Property<DateTime?>("IssuedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("issued_at_utc");

                    b.Property<long?>("IssuedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_by_user_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("paid_amount");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("ProductSubtotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("product_subtotal_amount");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("subtotal_amount");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TimeSubtotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("time_subtotal_amount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("InvoiceId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceCode")
                        .IsUnique();

                    b.HasIndex("IssuedByUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.InvoiceDiscount", b =>
                {
                    b.Property<long>("InvoiceDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_discount_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceDiscountId"));

                    b.Property<decimal>("AmountApplied")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("amount_applied");

                    b.Property<long?>("AppliedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptionSnapshot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description_snapshot");

                    b.Property<long>("DiscountId")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_id");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("InvoiceDiscountId");

                    b.HasIndex("AppliedByUserId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_discounts", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.InvoiceLine", b =>
                {
                    b.Property<long>("InvoiceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_line_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceLineId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("LineTotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("line_total_amount");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("line_type");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("quantity");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_lines", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.MediaAsset", b =>
                {
                    b.Property<long>("MediaAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("media_asset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MediaAssetId"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alt_text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("folder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("media_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("original_file_name");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("UploadedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("MediaAssetId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("media_assets", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("order_code");

                    b.Property<long>("OrderedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ordered_by_user_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("subtotal_amount");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("OrderedByUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SessionId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.OrderItem", b =>
                {
                    b.Property<long>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderItemId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("LineTotalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("line_total_amount");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("product_name_snapshot");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("unit_price_snapshot");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("PasswordResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("password_reset_token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PasswordResetTokenId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("RequestedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("requested_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("PasswordResetTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at_utc");

                    b.Property<long>("PaymentMethodId")
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int")
                        .HasColumnName("payment_status");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<long?>("ReceivedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("received_by_user_id");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("transaction_code");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("PaymentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("ReceivedByUserId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.PaymentMethod", b =>
                {
                    b.Property<long>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_method_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentMethodId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.PricingPlan", b =>
                {
                    b.Property<long>("PricingPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pricing_plan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PricingPlanId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ends_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("starts_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("PricingPlanId");

                    b.ToTable("pricing_plans", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.PricingPlanRule", b =>
                {
                    b.Property<long>("PricingPlanRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("pricing_plan_rule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PricingPlanRuleId"));

                    b.Property<int>("BillingBlockMinutes")
                        .HasColumnType("int")
                        .HasColumnName("billing_block_minutes");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("end_time");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("hourly_rate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("MinimumMinutes")
                        .HasColumnType("int")
                        .HasColumnName("minimum_minutes");

                    b.Property<long>("PricingPlanId")
                        .HasColumnType("bigint")
                        .HasColumnName("pricing_plan_id");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("start_time");

                    b.Property<long>("TableTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_type_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("PricingPlanRuleId");

                    b.HasIndex("TableTypeId");

                    b.HasIndex("PricingPlanId", "TableTypeId", "DayOfWeek", "StartTime")
                        .IsUnique();

                    b.ToTable("pricing_plan_rules", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsStockTracked")
                        .HasColumnType("bit")
                        .HasColumnName("is_stock_tracked");

                    b.Property<int?>("LowStockThreshold")
                        .HasColumnType("int")
                        .HasColumnName("low_stock_threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<long>("ProductCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_category_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("sku");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int")
                        .HasColumnName("stock_quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.ProductCategory", b =>
                {
                    b.Property<long>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("product_category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProductCategoryId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.RefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("refresh_token_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("revoked_by_ip");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "IsRevoked", "ExpiresAtUtc");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Session", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionId"));

                    b.Property<long?>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<long?>("ClosedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("closed_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long>("OpenedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("opened_by_user_id");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("session_code");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("SessionId");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("[booking_id] IS NOT NULL");

                    b.HasIndex("ClosedByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OpenedByUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SessionCode")
                        .IsUnique();

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.SessionTableAssignment", b =>
                {
                    b.Property<long>("SessionTableAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("session_table_assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionTableAssignmentId"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("amount");

                    b.Property<long?>("AssignedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ended_at_utc");

                    b.Property<decimal>("HourlyRateSnapshot")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)")
                        .HasColumnName("hourly_rate_snapshot");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<long?>("PricingPlanRuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("pricing_plan_rule_id");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at_utc");

                    b.Property<long>("TableId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("SessionTableAssignmentId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("PricingPlanRuleId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TableId");

                    b.ToTable("session_table_assignments", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.SiteSetting", b =>
                {
                    b.Property<long>("SiteSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("site_setting_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SiteSettingId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValueJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("setting_value_json");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("SiteSettingId");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("site_settings", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.TableType", b =>
                {
                    b.Property<long>("TableTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("table_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TableTypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DefaultCapacity")
                        .HasColumnType("int")
                        .HasColumnName("default_capacity");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("TableTypeId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("table_types", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at_utc");

                    b.Property<long?>("AssignedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by_user_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.VenueTable", b =>
                {
                    b.Property<long>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("table_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TableId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("OperationalStatus")
                        .HasColumnType("int")
                        .HasColumnName("operational_status");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("position_x");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("position_y");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("public_id");

                    b.Property<string>("TableCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("table_code");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("table_name");

                    b.Property<long>("TableTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("table_type_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("ZoneId")
                        .HasColumnType("bigint")
                        .HasColumnName("zone_id");

                    b.HasKey("TableId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("TableCode")
                        .IsUnique();

                    b.HasIndex("TableTypeId");

                    b.HasIndex("ZoneId");

                    b.ToTable("venue_tables", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Zone", b =>
                {
                    b.Property<long>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("zone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ZoneId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<long>("FloorId")
                        .HasColumnType("bigint")
                        .HasColumnName("floor_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ZoneId");

                    b.HasIndex("FloorId");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Booking", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PoolHub.Core.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.VenueTable", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolHub.Core.Entities.TableType", null)
                        .WithMany()
                        .HasForeignKey("TableTypeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PoolHub.Core.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Invoice", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("IssuedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PoolHub.Core.Entities.Session", null)
                        .WithOne()
                        .HasForeignKey("PoolHub.Core.Entities.Invoice", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.InvoiceDiscount", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AppliedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PoolHub.Core.Entities.Discount", null)
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.InvoiceLine", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.MediaAsset", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Notification", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Order", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OrderedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Payment", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.PaymentMethod", null)
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ReceivedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.PricingPlanRule", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.PricingPlan", null)
                        .WithMany()
                        .HasForeignKey("PricingPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.TableType", null)
                        .WithMany()
                        .HasForeignKey("TableTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Product", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Session", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.Booking", null)
                        .WithOne()
                        .HasForeignKey("PoolHub.Core.Entities.Session", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PoolHub.Core.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.SessionTableAssignment", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PoolHub.Core.Entities.PricingPlanRule", null)
                        .WithMany()
                        .HasForeignKey("PricingPlanRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PoolHub.Core.Entities.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.VenueTable", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.SiteSetting", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("PoolHub.Core.Entities.UserRole", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PoolHub.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.VenueTable", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.TableType", null)
                        .WithMany()
                        .HasForeignKey("TableTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PoolHub.Core.Entities.Zone", null)
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PoolHub.Core.Entities.Zone", b =>
                {
                    b.HasOne("PoolHub.Core.Entities.Floor", null)
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
